import Link from 'next/link'

import { ZefiMark } from '@/components/brand/zefi-mark'
import { SectionHeader } from '@/components/marketing/section-header'
import { RichText } from '@/components/ui/rich-text'
import { DEMO_CONVERSATIONS } from '@/lib/demo/fixtures'

const CAPABILITIES = [
  {
    title: 'Explains, without hedging',
    body: 'Protocol mechanics, contract behaviour, and the trade-offs a decision actually turns on — answered at the depth the question deserves.',
  },
  {
    title: 'Reads your wallet, and cites the time',
    body: 'Balances come from your connected wallet over configured RPC endpoints. Every figure carries the moment it was read.',
  },
  {
    title: 'Turns intent into a typed plan',
    body: 'A sentence becomes an action, networks, an asset, an amount and a recipient — validated against the registry before anything is built.',
  },
  {
    title: 'Says when it does not know',
    body: 'No live price, no balance read, no route quote — ZeFi reports the gap. It will not fill a missing number with a plausible one.',
  },
] as const

export function IntelligenceSection() {
  const conversation = DEMO_CONVERSATIONS[1]

  return (
    <section className="section relative overflow-hidden" id="intelligence">
      <div className="shell">
        <SectionHeader
          eyebrow="ZeFi Intelligence"
          title={
            <>
              The assistant that
              <br />
              knows what it cannot see
            </>
          }
          lede="Most crypto assistants are a chat box in front of a search index. ZeFi Intelligence is wired into a chain registry, a wallet reader, and a deterministic planner — and it is explicit about the boundary between them."
          action={
            <Link href="/intelligence" className="btn btn-ghost">
              Explore the intelligence layer
            </Link>
          }
        />

        <div className="mt-12 grid gap-4 lg:grid-cols-[minmax(0,1.15fr)_minmax(0,1fr)] lg:gap-6">
          {/* ── Conversation ─────────────────────────────────────────── */}
          <div className="panel-solid overflow-hidden">
            <div className="flex items-center justify-between gap-3 border-b border-line px-5 py-3.5">
              <div className="flex items-center gap-2">
                <ZefiMark className="h-4 w-4" />
                <span className="label-tech text-ink-soft">{conversation?.title}</span>
              </div>
              <span className="chip chip-ember">Illustrative</span>
            </div>

            <div className="space-y-4 p-5 sm:p-6">
              {conversation?.messages.map((message) =>
                message.role === 'user' ? (
                  <div key={message.id} className="flex justify-end">
                    <p className="max-w-[80%] rounded-2xl rounded-br-sm bg-ink px-4 py-2.5 text-[0.9375rem] leading-relaxed text-ivory">
                      {message.content}
                    </p>
                  </div>
                ) : (
                  <div key={message.id} className="flex gap-3">
                    <span className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border border-line bg-white">
                      <ZefiMark className="h-3.5 w-3.5" />
                    </span>
                    <RichText
                      content={message.content}
                      className="min-w-0 text-[0.9375rem] leading-relaxed text-ink-soft"
                    />
                  </div>
                ),
              )}
            </div>

            <div className="border-t border-line bg-ivory/60 px-5 py-3">
              <p className="text-[0.75rem] leading-relaxed text-ink-muted">
                Example exchange. In the product these figures come from a live read of your connected
                wallet, and the reply is generated by the configured model.
              </p>
            </div>
          </div>

          {/* ── Capabilities ─────────────────────────────────────────── */}
          <ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">
            {CAPABILITIES.map((capability) => (
              <li key={capability.title} className="panel-quiet p-5">
                <h3 className="text-[1.0625rem] leading-snug font-medium text-ink">{capability.title}</h3>
                <p className="mt-2 text-[0.875rem] leading-relaxed text-ink-soft">{capability.body}</p>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  )
}
